#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: in # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://q.shakeeb.in
playstore_link: https://play.google.com/store/apps/details?id=com.sarbakaf.qaafiyah
presskit_download_link:
  https://drive.google.com/file/d/1axjHoY5MWn8B5KxSowRmTbeQzZI5OZUu/view?usp=sharing # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Qaafiyah Expert
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Get the right tools for writing Urdu poetry at your fingertips.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Shakeeb Ahmad
your_link: https://shakeeb.in
your_city: Kamptee
email_address: SarbakafGroup@gmail.com
facebook_username: ShakesVision
twitter_username: ShakesVision
github_username: ShakesVision

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: One click solution
    description: Type the end-string and get thousands of rhymes
    fontawesome_icon_name: magic

  - title: Meter Feet / Wazn filter
    description: Filter for Urdu poetic meters
    fontawesome_icon_name: balance-scale

  - title: Multilingual
    description: Supports 4 scripts for search - Urdu, Farsi, Hindi & Roman.
    fontawesome_icon_name: language

  - title: Works offline
    description: Qaafiyah, Wazn for word, Words for wazn and regular expression search, Bayaaz & Design features, all are offline!
    fontawesome_icon_name: wifi-slash

  - title: Get feedback for your poetry
    description: A Taqti & Islah section to calculate poetic meters of poetry (Prosody عروض), along with online islah workshop
    fontawesome_icon_name: hands-praying

  - title: Dictionaries and Thesaurus (Tri-lingual)
    description: Multiple dictionaries and a thesaurus to look up meanings, pronunciations and synonyms (Urdu/Hindi/Roman)
    fontawesome_icon_name: book

  - title: Jot down your poetry
    description: A lightweight diary with offline "save" support
    fontawesome_icon_name: marker

  - title: Design
    description: Simple and elegant solution to design your poetry. Pretty and Justified!
    fontawesome_icon_name: palette

  - title: Awesome quotes and articles
    description: An online portal for awesome literary posts, updated periodically.
    fontawesome_icon_name: newspaper

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
